//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Script
{
    using System;
    using System.Xml;
    using System.Xml.Schema;
    using System.Collections.Generic;
    using HP.ST.Fwk.RunTimeFWK;
    using HP.ST.Fwk.RunTimeFWK.CheckpointFWK;
    using HP.ST.Fwk.RunTimeFWK.Utilities;
    using HP.ST.Ext.CheckpointLogicOperators;
    using HP.ST.Ext.BindingImpl.Getters;
    using HP.ST.Ext.BindingImpl.Setters;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK.Getters;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK.Setters;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK.PropInfo;
    
    
    public partial class WorkFlowScript
    {
        
        private void set_RESTActivityV24_checkpoints(STActivityBase activity)
        {
            // Checkpoint 1
            IVTDGetter actualValueGetter1 = new VTDXPathGetter(new VTDPropertyInfoBase("XMLResponse", "/*[local-name(.)='ArrayOfFlight'][1]/*[local-name(.)='Flight'][1]/*[local-name(.)='FlightNumber'][1]"), XmlTypeCode.UnsignedShort, false);
            IVTDSetter actualValueSetter1 = new VTDCheckpointSetter(XmlTypeCode.UnsignedShort);
            BindDirection actualBindDirection1 = new BindDirection(_flow.RESTActivityV24, actualValueGetter1, actualValueSetter1);
            CpValObj valueActualObject1 = new CpValObj(actualBindDirection1, XmlTypeCode.UnsignedShort, false);
            CpValObj valueExpectedObject1 = new CpValObj("0", XmlTypeCode.UnsignedShort);
            ValueCPRule cpRule1 = new ValueCPRule(valueActualObject1, valueExpectedObject1, PrimitiveTypeCP.LargerThan, ">", false);
            activity.AddCheckpointRule(cpRule1);

            // Checkpoint 2
            IVTDGetter actualValueGetter2 = new VTDObjectGetter(new VTDPropertyInfoBase("Output.GetFlights_OutputParam_FlightNo"));
            IVTDSetter actualValueSetter2 = new VTDCheckpointSetter(XmlTypeCode.Int);
            BindDirection actualBindDirection2 = new BindDirection(_flow.RESTActivityV24, actualValueGetter2, actualValueSetter2);
            CpValObj valueActualObject2 = new CpValObj(actualBindDirection2, XmlTypeCode.Int, false);
            CpValObj valueExpectedObject2 = new CpValObj("", XmlTypeCode.Int);
            ValueCPRule cpRule2 = new ValueCPRule(valueActualObject2, valueExpectedObject2, PrimitiveTypeCP.NotEqualTo, "!=", false);
            activity.AddCheckpointRule(cpRule2);

        }
    }
}
