/***************************************************************
    *  DO NOT EDIT THIS FILE!
    *         
    *  This file is automatically generated by HP Service Test.
    *  Manually changing the contents of this file may result in 
    *  loss of information.
    *          
    *  To edit the test, open the file ‘APIWADL_Final.st’ 
    *  in HP Service Test.
     ***************************************************************/
    
    namespace Script
    {
    using System;
    using System.Text;
    using System.Threading;
    using System.Xml;
    using System.Xml.Schema;
    using HP.ST.Fwk.ReporterFWK;
    using HP.ST.Shared.Utilities;
    using HP.ST.Ext.BindingImpl.Getters;
    using HP.ST.Ext.BindingImpl.Setters;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK.PropInfo;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK.Getters;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK.Setters;
    using HP.ST.Fwk.RunTimeFWK;
    using HP.ST.Fwk.RunTimeFWK.Utilities;
    using HP.ST.Fwk.RunTimeFWK.HelperClasses;
    using HP.ST.Fwk.RunTimeFWK.CompositeActivities;
    using HP.ST.Ext.BindingImpl.Setters.DataSourceSetters;
    using HP.ST.Fwk.JVMLoader;
    using System.IO;
    using System.Collections.Generic;
    using System.Reflection;
    using HP.ST.Fwk.SOAReplayAPI;
    using HP.ST.Fwk.UFTLicensing;
    
    
    
    public partial class WorkFlowScript : STWorkFlowScriptBase
    {    
    	TestUserCode _userCode = null;
    	TestEntities _flow = null;
    	static Reporter reporter;
    	int reportLevelInTree;
        HP.ST.Fwk.ReportCreator.QTPEngine.QTPEngineReportCreator reportCreator;
    	
    	public BindDirection bind_dir36 = null;
        public BindDirection bind_dir37 = null;
        public BindDirection bind_dir38 = null;
        public BindDirection bind_dir39 = null;
        
        public IEnumerable<FeaturesGroup> LicensedFeatures
        {
        
        get
        {
        List<FeaturesGroup> features = new List<FeaturesGroup>();
        return features;
        
        }
        
        }
        
        public WorkFlowScript()
            : base(VuserClass.CommandLineArguments, new STRunTimeContext(), "test")
        {	
        	UpdateContextWithActionFolder(String.Empty);
        	
        }
        
        public WorkFlowScript(ISTRunTimeContext ctx)
            : base(VuserClass.CommandLineArguments, ctx, "test")
            
        {
        	this._context = ctx;
        	UpdateContextWithActionFolder(String.Empty);
        	UpdateTestSettings(ctx);
        }
        
        internal void InitializeComponent()
        {
        	LoadInput();
        	
        	InitReport();
        	
        	InitializeEncryptionManagerValues();
        
        	_userCode = new TestUserCode();
            _flow = _userCode;
            _flow.Context=this._context;
            
            
        
        	_flow.StartActivity1 = new HP.ST.Ext.BasicActivities.StartActivity(_context,"StartActivity1");
            _flow.Loop2 = new HP.ST.Fwk.RunTimeFWK.CompositeActivities.Loop<Loop2Input>(_context,"Loop2",LoopType.For);
            _flow.EndActivity3 = new HP.ST.Ext.BasicActivities.EndActivity(_context,"EndActivity3");
            _flow.Sequence11 = new HP.ST.Fwk.RunTimeFWK.CompositeActivities.Sequence(_context,"Sequence11");
            _flow.CallSTTest4 = new HP.ST.Ext.STRunnerActivity.RunSTActivity(_context,"CallSTTest4",false);
            _flow.SetTestVariableActivity6 = new HP.ST.Ext.BasicActivities.SetTestVariableActivity(_context,"SetTestVariableActivity6");
            _flow.ReportMessageActivity7 = new HP.ST.Ext.BasicActivities.ReportMessageActivity(_context,"ReportMessageActivity7");
            _flow.CallSTTest5 = new HP.ST.Ext.STRunnerActivity.RunSTActivity(_context,"CallSTTest5",false);
            _flow.ConcatenateStringsActivity10 = new HP.ST.Ext.BasicActivities.ConcatenateStringsActivity(_context,"ConcatenateStringsActivity10");
            _flow.ReportMessageActivity9 = new HP.ST.Ext.BasicActivities.ReportMessageActivity(_context,"ReportMessageActivity9");
            _flow.StartActivity1.Comment = @"";
            _flow.StartActivity1.IconPath = @"AddIns\ServiceTest\BasicActivities\toolbox_code_activity.png";
            _flow.StartActivity1.Name = @"Start";
            _flow.StartActivity1.JVM = new HP.ST.Ext.BasicActivities.JVMProperties();
            _flow.StartActivity1.IsJavaUsed = false;
            _flow.StartActivity1.JVM.Classpath = @"%CLASSPATH%";
            _flow.StartActivity1.JVM.AdditionalVMParameters = @"";
            _flow.StartActivity1.JMS = new HP.ST.Ext.BasicActivities.JMSProperties();
            _flow.StartActivity1.IsJmsUsed = false;
            _flow.StartActivity1.JMS.JNDIContextFactory = @"<Select...>";
            _flow.StartActivity1.JMS.JNDIProviderUrl = @"";
            _flow.StartActivity1.JMS.JMSConnectionFactory = @"";
            _flow.StartActivity1.JMS.SecurityPrincipal = @"";
            _flow.StartActivity1.JMS.SecurityCredentials = @"";
            _flow.StartActivity1.JMS.ConnectionsPerProcess = @"1";
            _flow.StartActivity1.JMS.TimeoutOptions = @"DN_User_defined_Timeout";
            _flow.StartActivity1.JMS.UserTimeout = @"20";
            _flow.StartActivity1.JMS.GenerateAutoSelector = @"No";
            this.Activities.Add (_flow.StartActivity1);
            _flow.Loop2.ConditionAsString = @"Run for 1 iteration";
            _flow.Loop2.NumberOfIterations = (int)1;
            _flow.Loop2.Comment = @"";
            _flow.Loop2.IconPath = @"AddIns\ServiceTest\BasicActivities\toolbox_loop.png";
            _flow.Loop2.Name = @"Test Flow";
            _flow.Loop2.Activities.Add (_flow.Sequence11);
            this.Activities.Add (_flow.Loop2);
            XmlDocument EndActivity3_ExecutionOutputParameters_Document = new XmlDocument();
            EndActivity3_ExecutionOutputParameters_Document.PreserveWhitespace = true;
            EndActivity3_ExecutionOutputParameters_Document.LoadXml(
@"<Arguments><DriverOutParam_ResNo></DriverOutParam_ResNo></Arguments>");
            _flow.EndActivity3.ExecutionOutputParameters = EndActivity3_ExecutionOutputParameters_Document;
            _flow.EndActivity3.Comment = @"";
            _flow.EndActivity3.IconPath = @"AddIns\ServiceTest\BasicActivities\toolbox_code_activity.png";
            _flow.EndActivity3.Name = @"End";
            this.Activities.Add (_flow.EndActivity3);
            _flow.Sequence11.Comment = @"";
            _flow.Sequence11.IconPath = @"";
            _flow.Sequence11.Name = @"Sequence11";
            _flow.Sequence11.Activities.Add (_flow.CallSTTest4);
            _flow.Sequence11.Activities.Add (_flow.SetTestVariableActivity6);
            _flow.Sequence11.Activities.Add (_flow.ReportMessageActivity7);
            _flow.Sequence11.Activities.Add (_flow.CallSTTest5);
            _flow.Sequence11.Activities.Add (_flow.ConcatenateStringsActivity10);
            _flow.Sequence11.Activities.Add (_flow.ReportMessageActivity9);
            _flow.CallSTTest4.Comment = @"";
            _flow.CallSTTest4.IconPath = @"AddIns\ServiceTest\STRunner\ictb_api_test_16x16.png";
            _flow.CallSTTest4.Name = @"APIWADL_GetFlights";
            _flow.CallSTTest4.ScriptPath = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallSTTest4.ScriptPath}")) ? @"..\APIWADL_GetFlights" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallSTTest4.ScriptPath}");
            _flow.CallSTTest4.ActionName = @"";
            _flow.CallSTTest4.ResultLocation = @"RunStReport\";
            _flow.SetTestVariableActivity6.VariableKey = @"DriverFlightNo";
            _flow.SetTestVariableActivity6.VariableValue = @"20279";
            _flow.SetTestVariableActivity6.Comment = @"";
            _flow.SetTestVariableActivity6.IconPath = @"AddIns\ServiceTest\BasicActivities\toolbox_setenv.png";
            _flow.SetTestVariableActivity6.Name = @"Set Test Variable6";
            _flow.SetTestVariableActivity6.AfterExecuteStepEvent += _userCode.SetTestVariableActivity6_OnAfterExecuteStepEvent;
            _flow.ReportMessageActivity7.Status = @"Done";
            _flow.ReportMessageActivity7.Message = @"{ENV:DriverFlightNo}";
            _flow.ReportMessageActivity7.Destination = @"ReportAndOutput";
            _flow.ReportMessageActivity7.Comment = @"";
            _flow.ReportMessageActivity7.IconPath = @"AddIns\ServiceTest\BasicActivities\toolbox_report_message.png";
            _flow.ReportMessageActivity7.Name = @"Report Message7";
            VTDPropertyInfoBase pi71 = new VTDPropertyInfoBase("DriverFlightNo");
            VTDBaseGetter binding_getter36 = new EnvironmentVariableGetter(pi71);
            VTDPropertyInfoBase pi72 = new VTDPropertyInfoBase("Message");
            VTDBaseSetter binding_setter36 = new VTDObjectSetter(pi72);
            binding_setter36 = new StringFormaterDecorator(binding_setter36,"{ENV:DriverFlightNo}");
            bind_dir36 = new BindDirection(_flow.StartActivity1,binding_getter36,binding_setter36,BindTargetType.ToInProperty);
            _flow.ReportMessageActivity7.InDirections.Add(bind_dir36);
            XmlDocument CallSTTest5_InputProperties_Document = new XmlDocument();
            CallSTTest5_InputProperties_Document.PreserveWhitespace = true;
            CallSTTest5_InputProperties_Document.LoadXml(
@"<Arguments><BookFlight_TestOutParam_FlightNo>{ENV:DriverFlightNo}</BookFlight_TestOutParam_FlightNo></Arguments>");
            _flow.CallSTTest5.InputProperties = CallSTTest5_InputProperties_Document;
            _flow.CallSTTest5.Comment = @"";
            _flow.CallSTTest5.IconPath = @"AddIns\ServiceTest\STRunner\ictb_api_test_16x16.png";
            _flow.CallSTTest5.Name = @"APIWADL_BookFlight";
            _flow.CallSTTest5.ScriptPath = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallSTTest5.ScriptPath}")) ? @"..\APIWADL_BookFlight" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallSTTest5.ScriptPath}");
            _flow.CallSTTest5.ActionName = @"";
            _flow.CallSTTest5.ResultLocation = @"RunStReport\";
            VTDPropertyInfoBase pi73 = new VTDPropertyInfoBase("DriverFlightNo");
            VTDBaseGetter binding_getter37 = new EnvironmentVariableGetter(pi73);
            VTDPropertyInfoBase pi74 = new VTDPropertyInfoBase("InputProperties","/*[local-name(.)='Arguments'][1]/*[local-name(.)='BookFlight_TestOutParam_FlightNo'][1]");
            VTDBaseSetter binding_setter37 = new VTDXPathSetter(pi74,XmlTypeCode.Int);
            bind_dir37 = new BindDirection(_flow.StartActivity1,binding_getter37,binding_setter37,BindTargetType.ToInProperty);
            _flow.CallSTTest5.InDirections.Add(bind_dir37);
            _flow.ConcatenateStringsActivity10.Prefix = @"Newly created order is: ";
            _flow.ConcatenateStringsActivity10.Suffix = @"{Step.OutputProperties.CallSTTest5.BookFlight_TestOutParam_ReservationNo}";
            _flow.ConcatenateStringsActivity10.Comment = @"";
            _flow.ConcatenateStringsActivity10.IconPath = @"AddIns\ServiceTest\BasicActivities\toolbox_concat.png";
            _flow.ConcatenateStringsActivity10.Name = @"Concatenate Strings10";
            VTDPropertyInfoBase pi75 = new VTDPropertyInfoBase("OutputProperties","/*[local-name(.)='Arguments'][1]/*[local-name(.)='BookFlight_TestOutParam_ReservationNo'][1]");
            VTDBaseGetter binding_getter38 = new VTDXPathGetter(pi75,XmlTypeCode.String);
            VTDPropertyInfoBase pi76 = new VTDPropertyInfoBase("Suffix");
            VTDBaseSetter binding_setter38 = new VTDObjectSetter(pi76);
            binding_setter38 = new StringFormaterDecorator(binding_setter38,"{Step.OutputProperties.CallSTTest5.BookFlight_TestOutParam_ReservationNo}");
            bind_dir38 = new BindDirection(_flow.CallSTTest5,binding_getter38,binding_setter38,BindTargetType.ToInProperty);
            _flow.ConcatenateStringsActivity10.InDirections.Add(bind_dir38);
            _flow.ReportMessageActivity9.Status = @"Done";
            _flow.ReportMessageActivity9.Message = @"{Step.OutputProperties.ConcatenateStringsActivity10.Result}";
            _flow.ReportMessageActivity9.Destination = @"ReportAndOutput";
            _flow.ReportMessageActivity9.Comment = @"";
            _flow.ReportMessageActivity9.IconPath = @"AddIns\ServiceTest\BasicActivities\toolbox_report_message.png";
            _flow.ReportMessageActivity9.Name = @"Report Message9";
            VTDPropertyInfoBase pi77 = new VTDPropertyInfoBase("Result");
            VTDBaseGetter binding_getter39 = new VTDObjectGetter(pi77);
            VTDPropertyInfoBase pi78 = new VTDPropertyInfoBase("Message");
            VTDBaseSetter binding_setter39 = new VTDObjectSetter(pi78);
            binding_setter39 = new StringFormaterDecorator(binding_setter39,"{Step.OutputProperties.ConcatenateStringsActivity10.Result}");
            bind_dir39 = new BindDirection(_flow.ConcatenateStringsActivity10,binding_getter39,binding_setter39,BindTargetType.ToInProperty);
            _flow.ReportMessageActivity9.InDirections.Add(bind_dir39);
            
        }
        
        internal void InitializeEncryptionManagerValues()
        {
        
        }
        	
    	bool useReport = true;
    
    	protected override STExecutionResult ExecuteStep()
        {
            return base.ExecuteStep();
        }
    
        public void Start()
        {
    	    try
    		{
    		  Workflow_Executing();
    		  this.ExecuteStep();
    		}
    		finally
    		{
    		  WorkFlowScript_Completed();
    		}
        }
    
    	private void InitReport()
    	{
    		if (useReport)
    		{	
    			// Intialize Reporter
    			string reportDBDir = Path.Combine(this._context.ReportDirectory, @"Report");
    			CleanupReport(reportDBDir);        	
    			string reportDBPath = Path.Combine(reportDBDir, "VTDReport.mdb");        	
    			if (reporter == null)
    			{
    				reporter = new Reporter(reportDBPath);
    			}
    			_context.Reporter = reporter;
    		}
    	}
    
        public static void CopyDirectory(string Src, string Dst)
        {
            String[] Files;
    
            if (Dst[Dst.Length - 1] != Path.DirectorySeparatorChar)
                Dst += Path.DirectorySeparatorChar;
            if (!Directory.Exists(Dst)) Directory.CreateDirectory(Dst);
            Files = Directory.GetFileSystemEntries(Src);
            foreach (string Element in Files)
            {
                // Sub directories
                if (Directory.Exists(Element))
                    CopyDirectory(Element, Dst + Path.GetFileName(Element));
                // Files in directory
                else
                    File.Copy(Element, Dst + Path.GetFileName(Element), true);
            }
        }
        
        private void CleanupReport(string reportDBDir)
        {   
    		if (useReport)
    		{             
    			string reportTemplateDir = Path.Combine(ServiceTestRunner.GetInstallPath(),@"bin\ReportResources");                
    			try
    			{
            		CopyDirectory(reportTemplateDir, reportDBDir);
    			}
    			catch //(Exception ex)
    			{
    				//ToDo: LoggingService.Warn("Report Cleanup Error", ex);
    			}
    		}
        }
    
        void Workflow_Executing()
        {   
        	InitReportNode();
                       
        }
    
    	private void InitReportNode()
    	{
    		if (useReport)
    		{	
        		// Init report creator
    			this.reportCreator = new HP.ST.Fwk.ReportCreator.QTPEngine.QTPEngineReportCreator();
    			this.reportLevelInTree = reportCreator.Init(_context.EnvironmentProfile.GetVariableValue("TestName"), _context);
                
    			STActivityBase activity = this;
    			string workflowID = activity.GetHashCode().ToString();
    			ReportNodeCreationData newNodeData =
    			new ReportNodeCreationData(workflowID, workflowID, DateTime.Now);
    			reporter.CreateReportNode(newNodeData);
            
    			ReportInfoData newReportData = new ReportInfoData(workflowID, ReportKeywords.TypeKeywordTag, this.GetType().ToString());
    			reporter.SendReportData(newReportData);
    			newReportData = new ReportInfoData(workflowID, ReportKeywords.NameKeywordTag, this.Name);
    			//TrackData(ReportInfoData.InfoDataTag, newReportData);
    			reporter.SendReportData(newReportData);            
            }
    	}
        
        void WorkFlowScript_Completed()
        {   
    		
    
    		CreateReportFiles();
    					
        	// Write all snapshots to disk
    		this._context.SnapshotManager.WriteSnapshotsToDisk();
    
    		OnExecutionCompleted();
    		
        }
    
    	private void CreateReportFiles()
    	{
    		if (useReport)
    		{	
    			//Dispose reporter inorder to close connection to report DB
           		this._context.Reporter.Dispose();
            	
           		// Run report creator
    			reportCreator.RunOnDBAndCreateFiles();
    		}
    	}
    
        
        void Workflow_Faulting()
        {
    		
    
    		CreateReportFiles();
            // Write all snapshots to disk
    		this._context.SnapshotManager.WriteSnapshotsToDisk();
           
    		OnExecutionCompleted();
        }
    
    	protected override QcSystemVariables GetRuntimeQcVariables(ISTRunTimeContext context)
    	{
    		return new HP.ST.Ext.BasicActivities.RuntimeQcVariables(this._context);
    	}
            
    	protected override TestSystemVariables GetTestSystemVariables(ISTRunTimeContext context)
    	{
    		return new HP.ST.Ext.BasicActivities.RuntimeTestVariables(this._context);
    	}
    
    	private void UpdateTestSettings(ISTRunTimeContext ctx)
        {
    		ctx.PropertyBag["StopTestOnStepFailure"] = true;
    	}
    }
    
    public partial class VuserClass
    {
    	public static string[] CommandLineArguments;
    	public static string[] DotNetResolverPaths;
    	
        public VuserClass()
        {
    				
    		AssemblyResolver.AddSTPathsToResolutionPaths();
    		AssemblyResolver.AttachToAppdomain();
        }
    
        private void AddAssemblyResolver()
        {
    		AssemblyResolver.AddTestPathToResolutionPaths(GetTestPath());
    		AssemblyResolver.AddPathsForAssemblyResolution(DotNetResolverPaths);
        }
    	
        public int STAction()
        {	
            AddAssemblyResolver();
            STRunTimeContext ctx = new STRunTimeContext(Directory.GetParent(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location)).FullName, string.Empty);
            WorkFlowScript script = new WorkFlowScript(ctx);
            script.InitializeComponent();
            script.Start();       
            
            return 0;
        }
        
        public void NotifyLicenseException(string msg)
        {
        		
    		try
    		{
    		    STRunTimeContext ctx = new STRunTimeContext(Directory.GetParent(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location)).FullName, string.Empty);
                WorkFlowScript script = new WorkFlowScript(ctx);
                script.InitializeComponent();
                script.Context.ReplayClient.OnLicenseFailure(msg);
                
            }
            catch (Exception)
            {
    			// ToDo: log the error message
            }        
        }
    
    	 protected string GetTestPath()
            {
                if (CommandLineArguments != null)
                {
                    for (int i = 0; i < CommandLineArguments.Length; i++)
                    {
                        if (CommandLineArguments[i].Equals("-test", StringComparison.OrdinalIgnoreCase))
                        {
                            return CommandLineArguments[i + 1];
                        }
                    }
                }
                return String.Empty;
            }
        
    }
    
    }
    